import { StyleSheet } from 'react-native';

const mono = 'Courier';

export const codeStyles = StyleSheet.create({
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#081422',
    borderBottomWidth: 1,
    borderBottomColor: '#13283c',
  },
  summary: { color: '#9cb5cc', fontSize: 12, fontWeight: '600', flexShrink: 1 },
  toolbarButtons: { flexDirection: 'row', gap: 6 },
  iconBtn: {
    minWidth: 32,
    height: 28,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#193959',
    backgroundColor: '#0e2338',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: { color: '#00e5c8', fontSize: 12, fontWeight: '700' },

  fileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    backgroundColor: '#0c1f33',
    borderTopWidth: 1,
    borderTopColor: '#173654',
    borderBottomWidth: 1,
    borderBottomColor: '#173654',
  },
  chevron: { color: '#7b98b3', fontSize: 12, width: 12 },
  filePath: { color: '#d6e6f5', fontSize: 13, fontWeight: '700', fontFamily: mono },
  fileMeta: { color: '#7b98b3', fontSize: 10 },
  fileBadge: {
    color: '#57c7ff',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: '#1d4f72',
    borderRadius: 4,
    paddingHorizontal: 4,
  },
  noteCount: { color: '#ffcb6b', fontSize: 11, fontWeight: '700' },
  addCount: { color: '#5af78e', fontSize: 11, fontWeight: '700', fontFamily: mono },
  delCount: { color: '#ff5c57', fontSize: 11, fontWeight: '700', fontFamily: mono },

  hunkRow: { backgroundColor: '#0b1a2b', paddingHorizontal: 10, paddingVertical: 4 },
  hunkText: { color: '#57c7ff', fontSize: 11, fontFamily: mono },
  lineRow: { flexDirection: 'row', paddingVertical: 1, paddingRight: 8 },
  addRow: { backgroundColor: 'rgba(90, 247, 142, 0.08)' },
  delRow: { backgroundColor: 'rgba(255, 92, 87, 0.09)' },
  lineNo: { width: 34, textAlign: 'right', color: '#41607c', fontSize: 10, fontFamily: mono, paddingRight: 4, paddingTop: 1 },
  sign: { width: 14, textAlign: 'center', color: '#7b98b3', fontSize: 12, fontFamily: mono },
  code: { flex: 1, color: '#c9d9e8', fontSize: 12, fontFamily: mono },
  addText: { color: '#5af78e' },
  delText: { color: '#ff7b76' },

  noteBubble: {
    marginLeft: 48,
    marginRight: 10,
    marginVertical: 4,
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 203, 107, 0.1)',
    borderLeftWidth: 3,
    borderLeftColor: '#ffcb6b',
  },
  noteAuthor: { color: '#ffcb6b', fontSize: 10, fontWeight: '700', marginBottom: 2 },
  noteBody: { color: '#f1e6c8', fontSize: 12 },

  sendBar: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0c2238',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffcb6b',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sendBarText: { color: '#ffcb6b', fontSize: 13, fontWeight: '700' },
  sendBtn: { backgroundColor: '#00e5c8', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  sendBtnText: { color: '#05111c', fontWeight: '800', fontSize: 13 },

  emptyCard: {
    margin: 16,
    padding: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#173654',
    backgroundColor: '#081626',
    alignItems: 'center',
  },
  emptyTitle: { color: '#d6e6f5', fontSize: 15, fontWeight: '700', marginBottom: 4 },
  emptySub: { color: '#7b96ad', fontSize: 12, textAlign: 'center' },

  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.55)' },
  sheet: {
    backgroundColor: '#0a1828',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderColor: '#1d3e5f',
    maxHeight: '90%',
  },
  sheetTitle: { color: '#00e5c8', fontSize: 18, fontWeight: '800' },
  sheetSub: { color: '#7b96ad', fontSize: 12, marginTop: 2, marginBottom: 10, fontFamily: mono },
  sheetSection: { color: '#7f9db8', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', marginTop: 10, marginBottom: 6 },
  snippet: { backgroundColor: '#050c16', borderRadius: 8, padding: 8, marginBottom: 10 },
  snippetText: { color: '#c9d9e8', fontFamily: mono, fontSize: 12 },
  sheetInput: {
    minHeight: 90,
    backgroundColor: '#050c16',
    borderWidth: 1,
    borderColor: '#193959',
    borderRadius: 10,
    color: '#f0f6fc',
    padding: 10,
    fontSize: 14,
    textAlignVertical: 'top',
  },
  sheetActions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 14 },
  sheetPrimary: { backgroundColor: '#00e5c8', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 9 },
  sheetPrimaryText: { color: '#05111c', fontWeight: '800' },
  sheetCancel: { paddingHorizontal: 12, paddingVertical: 9 },
  sheetCancelText: { color: '#9cb5cc', fontWeight: '600' },
  sheetDanger: { flex: 1, paddingVertical: 9 },
  sheetDangerText: { color: '#ff6b6b', fontWeight: '600' },
  sheetOption: {
    borderWidth: 1,
    borderColor: '#1d3e5f',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    backgroundColor: '#0c1f33',
  },
  sheetOptionTitle: { color: '#d6e6f5', fontSize: 14, fontWeight: '700' },
  sheetOptionSub: { color: '#7b96ad', fontSize: 11, marginTop: 2 },
  presetWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  sheetChip: {
    borderWidth: 1,
    borderColor: '#00e5c8',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'rgba(0, 229, 200, 0.1)',
  },
  sheetChipText: { color: '#00e5c8', fontWeight: '700', fontSize: 13 },
  sheetLink: { color: '#7f9db8', fontSize: 12, fontWeight: '600', marginTop: 6 },
  promptPreview: { maxHeight: 180, backgroundColor: '#050c16', borderRadius: 8, padding: 8, marginTop: 6 },

  treeRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingRight: 12, borderBottomWidth: 1, borderBottomColor: '#0c1a29' },
  treeIcon: { width: 22, fontSize: 13 },
  treeName: { flex: 1, color: '#c9d9e8', fontSize: 13, fontFamily: mono },
  treeDir: { color: '#d6e6f5', fontWeight: '700' },
  treeStatus: { fontSize: 11, fontWeight: '800', fontFamily: mono, marginLeft: 6 },
  treeInfo: { color: '#5c768d', fontSize: 12, fontStyle: 'italic', paddingVertical: 6 },
  rootLabel: { color: '#d6e6f5', fontSize: 12, fontWeight: '700', fontFamily: mono, flexShrink: 1 },

  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: '#091829',
    borderBottomWidth: 1,
    borderBottomColor: '#173654',
  },
  previewPath: { flex: 1, color: '#d6e6f5', fontSize: 13, fontWeight: '700', fontFamily: mono },
  previewMeta: { color: '#7b96ad', fontSize: 11, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#081422' },
  previewLine: { flexDirection: 'row' },
  previewNo: { width: 40, textAlign: 'right', color: '#41607c', fontSize: 11, fontFamily: mono, paddingRight: 8 },
  previewCode: { color: '#c9d9e8', fontSize: 12, fontFamily: mono },
});
